Repository chaosblade-io/chaosblade-exec-os, pull requests merged in 2020-09, with the labels that each got.

#48 bugfix: fix stopping memory load without mode flag
  exec/bin/burnmem/burnmem.go
  exec/mem.go
Labels: bug

#50 bugfix: fix stopping disk io burning failed
  exec/bin/burnio/burnio.go
Labels: bug

#49 feature:improvement the action use case
  exec/cpu.go
  exec/disk.go
  exec/disk_burn.go
  exec/disk_fill.go
  exec/file.go
  exec/file_add.go
  exec/file_append.go
  exec/file_chmod.go
  exec/file_delete.go
  exec/file_move.go
  exec/mem.go
  exec/network.go
  exec/network_corrupt.go
  exec/network_delay.go
  exec/network_dns.go
  exec/network_drop.go
  exec/network_duplicate.go
  exec/network_loss.go
  exec/network_occupy.go
  exec/network_reorder.go
  exec/process.go
  exec/process_kill.go
  exec/process_stop.go
  exec/script.go
  exec/script_delay.go
  exec/script_exit.go
  go.mod
  go.sum
Labels: documentation

#51 add ssh channel exector
  build/spec.go
  exec/executor_ssh.go
  exec/model/model.go
  go.mod
  go.sum
  version/version.go
Labels: enhancement

#54 SSH channel password ciphertext input
  exec/executor_ssh.go
  go.mod
Labels: enhancement

#52 feature: slim down the blade toolkit
  Makefile
Labels: enhancement

#55 feature: add programs field in exp model and split yaml with bin file
  Makefile
  exec/bin/burncpu/burncpu.go
  exec/bin/burncpu/burncpu_test.go
  exec/bin/burncpu/forlinux/burncpu.go
  exec/bin/burncpu/forlinux/burncpu_test.go
  exec/bin/burnio/burnio.go
  exec/bin/burnmem/burnmem.go
  exec/bin/file/addfile/addfile.go
  exec/bin/file/appendfile/appendfile.go
  exec/bin/file/chmodfile/chmodfile.go
  exec/bin/file/deletefile/deletefile.go
  exec/bin/file/movefile/movefile.go
  exec/bin/filldisk/filldisk.go
  exec/cpu.go
  exec/disk_burn.go
  exec/disk_fill.go
  exec/executor_ssh.go
  exec/file.go
  exec/file_add.go
  exec/file_append.go
  exec/file_chmod.go
  exec/file_delete.go
  exec/file_move.go
  exec/mem.go
  exec/network.go
  exec/network_corrupt.go
  exec/network_delay.go
  exec/network_dns.go
  exec/network_drop.go
  exec/network_duplicate.go
  exec/network_loss.go
  exec/network_occupy.go
  exec/network_reorder.go
  exec/process_kill.go
  exec/process_stop.go
  exec/script_delay.go
  exec/script_exit.go
  go.mod
  go.sum
Labels: enhancement

#56 chore: update version to 0.7.0 and check ifconfig command avaliable
  Makefile
  exec/bin/tcnetwork/tcnetwork.go
  go.mod
  go.sum
Labels: enhancement
